-- MySQL dump 10.11
--
-- Host: localhost    Database: opusproduction
-- ------------------------------------------------------
-- Server version	5.0.32-Debian_7etch5-log

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


--
-- Test ID field
--
-- TODO: We will be coming back to debconf these first two...

INSERT INTO `user` (real_name, salutation, firstname, lastname, username, password, user_type, id) VALUES('OPUS Front Desk', 'OPUS', 'Front', 'Desk', 'admin', '5f4dcc3b5aa765d61d8327deb882cf99', 'root', 1);

--
-- Dumping data for table `admins`
--

INSERT INTO `admins` (position, user_id) values('administrator', 1);


--
-- Dumping data for table `help`
--

LOCK TABLES `help` WRITE;
/*!40000 ALTER TABLE `help` DISABLE KEYS */;
INSERT INTO `help` VALUES (1,'XMLSyntax',NULL,NULL,'Guidance on how to write XML code','In some cases where you may need to enter a considerable quantity of text in\r\nsome fields the website it is often desireable for you to have\r\nsome control over the formatting of that text.\r\n<BR/>\r\n\r\nFor this purpose some XML style tags (similar to HTML) are permitted in these fields.\r\nIf you have some familiarity with HTML you should find this very easy to deal\r\nwith. Of course you need not use any tags at all, but in this case the website\r\nwill format the text as it sees fit.\r\n<BR/>\r\n\r\n<h4>Tag format</h4>\r\n\r\nJust as in HTML, the tags take the form of a control word encased between &lt; and\r\n&gt;. For example\r\n\r\n<BR/><BR/><TT>\r\n&lt;CENTER&gt;\r\n</TT>\r\n<BR/><BR/>\r\n\r\nwill cause all text following it to appear centered in the screen. This effect will\r\nstop when the corresponding tag\r\n\r\n<BR/><BR/><TT>\r\n&lt;/CENTER&gt;\r\n</TT>\r\n<BR/><BR/>\r\n!
 \r\nis met in the text.\r\n\r\n<h4>Centred text</h4>\r\n\r\nAs just desribed, to cause some text to appear in the center of the available space, place it between\r\nthe tags\r\n\r\n<BR/><BR/>\r\n<TT>&lt;CENTER&gt;This will appear in the centre.&lt;/CENTER&gt;</TT>\r\n<BR/><BR/>\r\n\r\nNote that although CENTER is spelt in the American manner here, the British\r\nEnglish CENTRE is also supported.\r\n\r\n<h4>Titles</h4>\r\n\r\nIf you wish to provide a subtitle for some text to follow, place it between the tags\r\n\r\n<BR/><BR/>\r\n<TT>&lt;TITLE&gt;This will appear as a title.&lt;/TITLE&gt;</TT>\r\n<BR/><BR/>\r\n\r\n<h4>Type-writer formatting</h4>\r\n\r\nIf you want a section of text to appear in fixed-width fonts (because you want\r\nsome elements to line up for example) use the tags\r\n\r\n<BR/><BR/>\r\n<TT>&lt;PRE&gt;This will appear in fixed width.&lt;/PRE&gt;</TT>\r\n<BR/><BR/>\r\n\r\nIn fact this set of tags means that text between them should appear exactly as\r\nyou ha!
 ve typed it, complete with new lines. For those people more familiar w
ith HTML tags the tags <TT>&lt;TT&gt;</TT> and \r\n<TT>&lt;/TT&gt;</TT> are also\r\nsupported with their original meaning.\r\n\r\n<h4>Taking a new line</h4>\r\n\r\nWhen you take a new line in the field window this does not mean the displayed text\r\nwill take a new line. This is to allow you to split lines to make them easy to\r\nread in the small window.\r\nIf you want to force a new line simply use<BR/><BR/>\r\n\r\n<TT>&lt;BR&gt;</TT> or the more correct <TT>&lt;BR/&gt;</TT>\r\n\r\nbut both forms are supported.\r\n\r\n<h4>Bold text</h4>\r\n\r\nIf you wish to emphasis a small section of text by making it bold (not necessary for titles please note) then you can use the following.\r\n<BR/><BR/>\r\n\r\n<TT>&lt;B&gt;</TT>This will be bold.\r\n<TT>&lt;/B&gt;</TT><BR/>\r\n\r\n<h4>Example</h4>\r\n\r\nHere is a sample of how the notes field for a course might be formatted.\r\n\r\n<BR/><BR/>\r\n<TT>\r\n&lt;CENTER&gt;<BR/>\r\n&lt;TITLE&gt;Placement Opportunity&lt;/TITLE&gt;<BR/>\r\nW!
 e are happy to announce that we at<BR/>\r\n&lt;B&gt;MicroBanana&lt;/B&gt; are looking<BR/>\r\nfor engineering students to help push<BR/>\r\nforward our ground-breaking research<BR/>\r\nin micro-integrated bananas.<BR/>\r\n&lt;/CENTER&gt;<BR/>\r\n&lt;BR/&gt;<BR/>\r\nMore information is given below.<BR/>\r\n&lt;PRE&gt;<BR/>\r\n<PRE>Job                             Salary\r\nBanana Manufacturing Engineer   20 bananas per month\r\nBanana Research Engineer        25 bananas per month</PRE>\r\n&lt;/PRE&gt;<BR>\r\n</TT>\r\n\r\nThis will appear as shown below.\r\n\r\n\r\n<h4>Placement Opportunity</h4>\r\nWe are happy to announce that we at\r\n<B>MicroBanana</B> are looking\r\nfor engineering students to help push\r\nforward our ground-breaking research\r\nin micro-integrated bananas.\r\n\r\n<BR/>\r\nMore information is given below.\r\n<PRE>\r\n\r\nJob                             Salary\r\nBanana Manufacturing Engineer   20 bananas per month\r\nBanana Research Engineer        25 bana!
 nas per month\r\n</PRE>\r\n',1),(1,'RootManageCSVMapping',0,'admin','M
ore detailed help on how to set up a CSV Mapping','<p>\r\nCSV Mappings are usually a way of mapping your own University format CSV files to a &quot;standard&quot; format used by OPUS. Note however, that your original file format can really be any text file which has one student per line. It\'s just as practical to use TSV or similar formats.Ã‚Â­</p>\r\n  <p> To set up a mapping, you will need to understand <a target=\"blank\" href=\"http://www.php.net/manual/en/reference.pcre.pattern.syntax.php\">regular expressions</a>, as used by the <a target=\"blank\" href=\"http://www.php.net/manual/en/function.preg-replace.php\">preg_replace</a> function in PHP. If you don\'t, it is strongly recommended you file a service ticket or ask a member of IT staff to help you set this up; regular expressions are a relatively complex concept if your format requires anything but the simplest manipulation.\r\n    <br /></p>\r\n  <p>OPUS expects the replacement line to map to the following:</p>\r\!
 n  <p>&quot;year_of_study&quot;,\r\n    \r\n    \r\n    \r\n    \r\n    <br />&quot;student_reg_number&quot;,\r\n    \r\n    \r\n    \r\n    \r\n    <br />&quot;title&quot;,\r\n    \r\n    \r\n    \r\n    \r\n    <br />&quot;firstname&quot;,\r\n    \r\n    \r\n    \r\n    \r\n    <br />&quot;lastname&quot;,\r\n    \r\n    \r\n    \r\n    \r\n    <br />&quot;email&quot;,\r\n    \r\n    \r\n    \r\n    \r\n    <br />&quot;programme_code&quot;,\r\n    \r\n    \r\n    \r\n    \r\n    <br />&quot;disability_code&quot;\r\n    \r\n    \r\n    \r\n    \r\n    \r\n    <br /></p>\r\n  <p>&nbsp;</p>\r\n  <p>all on one line. Note that if you don\'t have information about one of these, you should include the quotes with no content &quot;&quot;. This functionality is on this menu since errors here will generate errors in the student import functionality. </p>',70),(1,'ContactCompanyBasic',NULL,NULL,'Company Editor Basics tab (Contacts)','test',2),(1,'CompanyBasic',NULL,NULL,'Company Edit!
 or Basic tab','You can use this form to edit the company brief.\r\nIt 
is possible to use some special codes to help\r\nimprove the layout of the information when it is shown.<BR/>\r\nNote that when you make alterations to your entry\r\nthe system will automatically notify students that\r\nlogin to the system that your information has\r\nbeen updated.',3),(1,'StudentCVPersonal',NULL,'student','Student CV Personal details page','This page is used to enter some of your basic personal information.<BR/><BR/>\r\nYou should make sure that you have correctly spelt your email address and that it is able to receive mail at any time.<BR/><BR/>\r\nPlease take the time to replace your initials with your first name.<BR/><BR/>',4),(1,'StudentCVContacts',NULL,'student','Student CV Contact Details','Please enter your contact details on this page. If your term time address is the same as your home address just leave those fields blank.\r\n',5),(1,'StudentCVEducation',NULL,'student','Student CV Educational Details','Enter in your educational history. Please note!
  \r\nthat at current the one page PDF view of your \r\nCV will only show the most recent two of your \r\neducational records, but you may enter in more \r\nfor the HTML view or for future expansion.\r\n<BR/><BR/>\r\nYou should enter results in groups based on \r\nwhere you achieved your qualifications and in \r\nwhat year you achieved them. For example, enter\r\nin the appropriate location and year for your\r\n\'A\' levels. Once you have done this you should\r\nthen choose <B>Edit Results</B> to record\r\nresults obtained at that place and time.\r\n',6),(1,'StudentCVEducationResults',NULL,'student','Student CV Eductional Results Editing','Use this page to enter results for a particular\r\neducational period.<BR/><BR/>\r\nType in the subject and the grade and hit submit\r\nfor each grade.<BR/><BR/>\r\nGrades will be shown in alphabetical order, or \r\nin descending numerical order if percentages are\r\nentered on the actual produced CV.',7),(1,'ContactHome',NULL,NULL,'Compan!
 y Contact Home Page, first few paragraphs','Welcome to OPUS - the mana
gement system for all aspects of work-integrated learning and placement - developed at the University of Ulster, School of Electrical and Mechanical Engineering.<BR><BR>\r\n\r\nIf you need more information or help on finding students for your opportunity or advertising your vacancies please contact our staff by using the help directory link at the bottom of the page.<BR><BR>\r\n\r\nYou can use this site to:\r\n<ul>\r\n  <li>edit the details about your company that you wish to advertise to students;</li>\r\n  <li>add and edit information about placement vacancies you wish to offer;</li>\r\n  <li>view and edit information about the contacts who act for your company;</li>\r\n  <li>view lists of students applying for your vacancy online, invite a shortlist to interview and inform them of your decisions;</li>\r\n  <li>view RESOURCES using the menu on the left to get more information about our courses and placement procedures;</li>\r\n  <li>and more.</li>\r\n</ul>\r\nPlease do not!
  hesitate to ask us for help if you need it.\r\n',8),(1,'StudentCVWork',NULL,'student','Student CV Work Experience Help','This page is used for detailing any periods of \r\nwork experience you may have.<BR/><BR/>\r\n\r\nEach period should be entered as a separate\r\npiece of information using the form at the \r\nbottom of the page.<BR/><BR/>\r\n\r\nWork experience will be shown in your PDF CV\r\nordered so that the most recent experience \r\nappears at the top.',9),(1,'StudentCVOther',NULL,'student','Student CV Other details page','You should use this page to store information\r\nthat does not fit into the other categories\r\nprovided. Make such information meaningful, \r\ndon\'t fill in fields where you have nothing\r\nuseful to say. Any empty fields are not printed\r\non the final CV.<BR/><BR/>\r\n\r\n<h4>Activities</h4><BR/><BR/>\r\n\r\nIn activities you should detail other hobbies\r\nand interests you might have, or memberships of\r\nuniversity societies or clubs.<BR/><!
 BR/>\r\n\r\n<h4>Achievements</h4><BR/><BR/>\r\n\r\nAny awards or other
 achievements you may have\r\nshould be recorded here.<BR/><BR/>\r\n\r\n<h4>Career</h4><BR/><BR/>\r\n\r\nYou might use this field to discuss your future\r\ncareer plans, and where you would like to be in\r\nthe future.',10),(1,'StudentCVView',NULL,'student','Student CV View (HTML)','This page allows you to view your CV as it is\r\ncurrently set up in HTML form. Note that the\r\ncompanies will (at least primarily) see your CV\r\nin a one page PDF form.<BR/><BR/>\r\n\r\nIt is possible to view your CV in PDF form using\r\nan option on your menu, and you should ensure the\r\nCV looks appropriate when viewed in this \r\nmanner.<BR/><BR/>\r\n\r\nIn the HTML view it is possible to easily check\r\nwhat data you have entered, and you can show or \r\nhide each section by clicking on the appropriate\r\nlink.<BR/><BR/>\r\n\r\nTo edit a specific section simply click on the\r\nedit link or the appropriate link on the \r\nmenu.<BR/><BR/>',11),(1,'StudentHomePlaced2005',NULL,NULL,'Shown on !
 Student Home Page,  2005-06,  ALL PLACED',NULL,12),(1,'StudentHome2008',2,'','Messages for students unplaced 2008','<p><strong>Record Keeping</strong><br />You need to be methodically collecting evidence thoughout the year of your effort to get a suitable approved placement. You MUST keep copies of :</p>\r\n<ul>\r\n<li>all application forms submitted, with the job description; </li>\r\n<li>jobs (ie job descriptions) that you applied for by attaching your CV on the PDSystem; </li>\r\n<li>all correspondence with prospective employers on a speculative basis. </li>\r\n</ul>\r\n<p>Please also be aware that failure to turn up at any interview is automatically recorded on the PDSystem and will be produced as evidence of a lack of commitment on your part to fully engage in the placement process. This information will be available to members of staff who are requested to write a reference on your behalf.<br />Remember that obtaining a good placement is not only rewarding in itself b!
 ut also enhances your employability when entering the graduate employm
ent market. To achieve this goal requires commitment on your part in applying for placements and preparing well for the interviews. Bearing in mind the competitive nature of these placement opportunities you will need to make a lot of applications before you are successful.</p>',64),(1,'AdminLogViewer',NULL,'admin','Instructions for log viewing script','<B>Instructions</B><BR>\r\nThe placement system creates several log files\r\nin the course of its normal operation. These\r\nfiles are written to disk, but this utility\r\nallows limited viewing of these files.\r\n<BR><BR>\r\n<B>Log File</B><BR>\r\nThis specifies which file you wish to examine.\r\nThere is a separate log for general access,\r\nadmin usage, and reporting potential security\r\nbreaches. There is also a log for recording\r\ndebug information, but this isn\'t necessarily\r\nfor general usage.\r\n<BR><BR>\r\n<B>Search</B><BR>\r\nYou may wish to restrict output to show only\r\nlines that match a certain criterion. !
 To do this\r\nenter the expression in this field, which may\r\nbe a regular expression. If the field is blank\r\nthen all lines will be matched.\r\n<BR><BR>\r\n<B>Lines</B><BR>\r\nThe number of lines of output are also limited,\r\nby default to 100, but this can be varied. The\r\nmost recent lines are always displayed.\r\n',13),(1,'AdminStudentBroadsheet',NULL,NULL,'Help for generating student broadsheets','This option allows you to generate a broadsheet for students that are all nominally seeking placement in a given year, and who all share the same assessment regime. Due to the large amount of data that requires collation this procedure takes some time to complete.<BR><BR>\r\n\r\nThe HTML output will be very wide, but is useful for quick inspection of the broadsheet.<BR><BR>\r\n\r\nThe TSV output (Tab Separated Values) will allow you to download data to your PC, which can be loaded directly in Excel and similar programs, allowing you to do as much sorting, cropping and an!
 alysis as you wish.\r\n\r\n<BR>\r\n<BR>\r\n<B>Note</B> It is only poss
ible to create \r\nbroadsheets for students that share the same assessment regime. Depending on your permissions some students may not be available to you on listings.\r\n',14),(1,'AdminResourceAdd',NULL,NULL,'Guidance on adding resources for administrators','<h4>Resources</h4>\r\n\r\n<B>Filename to upload - </B>\r\n\r\nTo add a resource to the system you must first\r\nbrowse to the resource on your local computer. The system strictly controls the files that may be uploaded, although this is configurable.\r\n<BR/><BR/>\r\n\r\n<B>Filename shown to users - </B>\r\n\r\nThen, select a filename the user will see when they download the file. This filename need not be unique, but it <B>must</B> have an extension that is suitable for the type of file for security reasons. For example, an uploaded PDF file will\r\nnormally need to have a .pdf extension.\r\n<BR/><BR/>\r\n\r\n<B>Language - </B>\r\n\r\nSpecify the language of the uploaded resource.\r\n<BR/><BR/>\r\n\r\n<B>Lookup - </B>\!
 r\n\r\nSpecify a lookup expression for the resource with\r\nno spaces. This lookup should be unique within the\r\nlanguage, and is to allow multi-language support.\r\n<BR/><BR/>\r\n\r\n<B>Description - </B>\r\n\r\nThis will be shown to the user when listing\r\nresources, so it should be clear, and you may use\r\nthe fact that descriptions are alphabetically\r\nordered when shown to users.\r\n<BR/><BR/>\r\n\r\n<B>Author - </B>\r\n\r\nList any author in here if necessary.\r\n<BR/><BR/>\r\n\r\n<B>Copyright - </B>\r\n\r\nPlace any required copyright in here.\r\n<BR/><BR/>\r\n\r\n<B>Authorisation - </B>\r\n\r\nThis clause controls who can download this file.\r\nUsers that cannot download the file will not even\r\nsee it in the list. The string should take the\r\nform of a list of categories that can download\r\nthe resource, followed by a list of exceptions\r\npreceded by a \"!\" character. The categories \r\ninclude \"all\", \"student\" and \"contact\". An empty\r\nfield author!
 ises only administrators to download\r\na resource. Note that \"all\" 
still only permits\r\nauthenticated users to access the system.\r\n<BR/>\r\n\r\nFor example, the clause \"all !student\" will allow\r\nall logged in users to access the resources\r\nexcept for students.\r\n<BR/><BR/>\r\n',15),(1,'XMLTest',NULL,NULL,'This is for testing the new XML code - NOT FOR USE','<h4>This should be a title</h4><BR>\r\n<UL>\r\n<LI> This should be a listed item;\r\n<LI> and so should this;\r\n<LI> This should <B>have some bold in it</B>\r\n</UL>\r\n<OL>\r\n<LI> This will be an ordered list, I think\r\n<LI> or I hope so\r\n</OL>\r\n<A HREF=\"www.piglets.com\">There should be no link here...</A>',16),(1,'AdminAssessmentStructureEdit',NULL,NULL,'Shown for editing elements of an assessment structure','Warning<BR/><BR/>\r\n\r\nYou should only edit an assessment structure if you really understand what you are doing. Specifically, changing the <B>Name</B> of an element can break a script unless the corresponding name is changed in the front page.',17),(1,'StaffH!
 ome',NULL,NULL,'Shown to staff on their home page','Welcome to OPUS - the management system for all aspects of work-integrated learning and placement - developed at the University of Ulster, School of Electrical and Mechanical Engineering.\r\n',18),(1,'SupervisorHome',1,NULL,'Supervisor Home Page Announcement','<h4>ANNOUNCEMENTS</h4>\r\n<CENTRE>(This announcement last update: Fri 23 Mar 07 12:00)</CENTRE><BR><BR>\r\n\r\n<B>ROLE OF INDUSTRIAL SUPERVISOR</B><BR><BR>\r\nWelcome to the OPUS web site and thanks for your support to our Industrial Placement programme in the role as an \'Industrial Supervisor\'.<BR><BR>\r\n\r\nYou may find helpful guidance for this role at RESOURCES (see tab on left of this page), \'SEME06 - Guidance for the Industrial Supervisor 2006-07\'.  I ask that you review this document and support our student accordingly.<BR><BR>\r\n\r\n<B>EMPLOYER ASSESSMENT</B><BR><BR>\r\n\r\nYou are asked to complete the EMPLOYER ASSESSMENT (found under ASSESSMENT INFORM!
 ATION at the bottom of this page) for your student.  The online report
 should be completed towards the end of the placement period and certainly before <B>31 Jul 07</B> to enable compilation of marks.  There is no need for E Mails or printed copies - completion of the report online and \'submitting it\' is sufficient.<BR><BR>\r\n\r\nThanks or your support.<BR><BR>\r\n\r\nR J Laird (Ron)<BR>\r\nIndustrial Placement Coordinator<BR>\r\nSchool of Electrical and Mechanical Engineering<BR>\r\nTel: 44 (0)28 9036 6264<BR>\r\nE Mail: rj.laird@ulster.ac.uk<BR>',47),(1,'ContactHome',1,NULL,'Contact Home Page Announcement','<h4>ANNOUNCEMENTS</h4>\r\n<CENTRE>(This announcement last update: Mon 15 Oct 07 13:18)</CENTRE><BR><BR>\r\n\r\n<B>Student Placement 2008-09</B><BR>\r\nThe number of engineering students available for placements in 2008-09 is down on last year.  These students are now preparing their CVs and should be ready to apply for vacancies from end Oct 07 onwards.   They require a 12-month placement, starting Summer 2008.<BR><BR>\r\n\r\nI encourg!
 e companies to consider their placement requirements early and place their vacancy details on this web site later this year, preferably by Feb 08, even though the start date may be as late as Sep 08.<BR><BR>\r\n\r\nThere will be a small number of students who will be available to start placement in mid Jan 08.   Please contact me now to consider vacancy details and the selection process.<BR><BR>\r\n\r\nPlease contact me on any engineering placement matter.<BR><BR>\r\n\r\nR J Laird (Ron)<BR>\r\nIndustrial Placement Coordinator<BR>\r\nSchool of Electrical and Mechanical Engineering<BR>\r\nTel: 028 9036 6264<BR>\r\nE Mail: rj.laird@ulster.ac.uk\r\n',48),(1,'StudentHome2003',NULL,NULL,'Shown on Student Home Page, 2003-04, ALL','Welcome to OPUS - the management system for all aspects of work-integrated learning and placement - developed at the University of Ulster, School of Electrical and Mechanical Engineering.<BR><BR>\r\n\r\nNo further announcements.<BR><BR>\r\n\r\nR J Laird<!
 BR>\r\nIndustrial Placement Coordinator<BR>\r\nSchool of Electrical an
d Mechanical Engineering<BR>\r\nTel: 44 (0)28 9036 6264<BR>\r\nE Mail: rj.laird@ulster.ac.uk<BR>',19),(1,'StudentHome2007',1,NULL,'Student Home Announcement, 2007-08, SEME ALL',NULL,49),(1,'AdminImportCSV',NULL,NULL,'Guidance on importing students in bulk','<B>Please Note</B><BR><BR>\r\n\r\nThis script can now be used to import students directly from student records. Simply leave the filename blank and the system will attempt to load the students into the system - be patient, it may take some time.<BR><BR>\r\n\r\nThe old functionality is still present for now.\r\n\r\n',20),(1,'StudentHome2006',NULL,NULL,'Shown on Student Home Page, 2006-07, ALL','Welcome to OPUS - the management system for all aspects of work-integrated learning and placement - developed at the University of Ulster, School of Electrical and Mechanical Engineering.<BR><BR>\r\n',40),(1,'StudentHome2007',NULL,NULL,'Shown on Student Home Page, 2007-08, ALL','Welcome to OPUS - the management system for all aspect!
 s of work-integrated learning and placement - developed at the University of Ulster, School of Electrical and Mechanical Engineering.<BR><BR>\r\n',41),(1,'StudentHomePlaced',2,NULL,'Student Information','<B>How your Placement will be assessed.</B><BR><BR>\r\nPlacement Visits  30%<BR>\r\nEmployer Assessment  20%<BR>\r\nLogbook  10%<BR>\r\nTechnical Report  10%<BR>\r\nStudent Final Report	30%<BR><BR>\r\n<B>Guidance on Log Book and Technical Report</B><BR><BR>\r\nThe document Computing Schools: Student Guidance Notes, available in the Resources section, provides guidance on both Log Book, Technical Report and Placement Report.  Please note that the Technical Report is to be posted to your Placement Visitor at the end of January.<BR><BR>\r\n<B>Placement Visits</B><BR><BR>\r\nAll students will be allocated a placement visitor.  Once this allocation is done, contact details will be available on the PDSystem.  You should be contacted by your allocated visitor to arrange a first vi!
 sit by mid December.<BR><BR>\r\nMost second visits should be organised
 by 30th April.<BR><BR>\r\n',42),(1,'OpeningScreen',NULL,NULL,'Page displayed at root of whole site','This OPUS website manages the entire placement process for companies, students and academic staff.<BR><BR>\r\n<UL>\r\n<LI> <B>Companies</B> may promote placement vacancies and monitor applications for each vacancy, contact students for interviews and appoint.<BR></LI>\r\n<LI><B>Students</B> may create their CV and make it available to their selection of vacancies (ie apply).<BR></LI>\r\n<LI><B>Academic Staff</B> may manage their visits to students on placement, complete reports, allocate marks and provide assessment feedback.<BR></LI>\r\n<LI><B>Industrial Placement Coordinators</B> may manage the entire placement process and provide detailed resources on-line, including company application forms.<BR><BR></LI>\r\n</UL>\r\nThis system arranges Industrial Placement for students with specialisation in:<BR><BR>\r\n<ul>\r\n<LI>  mechanical engineering<BR></LI>\r\n<LI>  electrical !
 engineering<BR></LI>\r\n<LI>  electronic engineering<BR></LI>\r\n<LI>  software and IT skills<BR></LI>\r\n<LI>  internet communications<BR></LI>\r\n<LI>  biomedical engineering<BR></LI>\r\n<LI>  technology and design<BR></LI>\r\n<LI>  engineering management<BR>\r\n<LI>  and more<BR></LI>\r\n</ul>\r\n',21),(1,'NoteAddGuidance',0,'','Information about adding notes on items','<h4>Creating Notes - Please read carefully</h4>\r\n<p>Notes can be added which can be linked to various items on the system. Information in notes is subject to the data protection act, and creating a note is a one way process. They cannot be edited or deleted, so check everything very carefully before submission. Notes should not be added for trivial reasons and as a substitute for normal emails.\r\n<br /></p>\r\n<h4>Summary</h4>\r\n<p>The summary is a single line that should reflect \r\nthe nature of the main note, it is displayed in\r\nlistings of notes. Searches will match words\r\nin the summary or th!
 e main text.</p>\r\n<h4>Contents</h4>\r\n<p>This is the main informati
on for the note. A note\r\ncan be linked to several items so be specific\r\nwhich people or items you are referring to and\r\navoid pronouns that could be ambiguous. If the summary is sufficiently descriptive this field can be empty.</p>\r\n<h4>Authorisation</h4>\r\n<p>Notwithstanding the comments concerning the data protection act above, many notes have a limited readership. Admin users, and the author of a \r\nnote can always read that note. Other users can view the note only if (1) They are linked to the note (or their company is) AND (2) their category of user is mentioned in this field.\r\nThus the field could read \"company staff\" and would mean that linked company contacts and staff members could view the note.</p>',22),(1,'AdminAdminRootList',NULL,'admin','Shown in Admin editor before root user listing','The following are root or super-admin users on the system. They have no defined default policy because they are not bound by the policy security system. Root users !
 have access to all aspects of the system without limitation. Users should <B>not</B> be given root users without proper training and preferably experience with lesser users.<BR><BR>',23),(1,'AdminHome',NULL,'admin','Welcome message for Admin Users','<p>\r\nWelcome. You are an administrator user on this system. This user is constrained by a security policy, and additionally may only be able to interact with given programmes and schools. Contact a super-administrator if you feel you do not have the access you need.</p>\r\n  <p>Above, you will see you main menu, which you will use to manipulate OPUS. The sections are:</p>\r\n  <ul>\r\n    <li><strong>home</strong> which contains this page, an ability to look at company activity and change your password;</li>\r\n    <li><strong>directories</strong> which will be the main menu you use day-to-day to work with students, companies and vacancies;</li>\r\n    <li><strong>information</strong> which is used to look as status and get re!
 ports;</li>\r\n    <li><strong>configuration</strong> which will be ne
eded to set up OPUS and modify it\'s behaviour;</li>\r\n    <li><strong>advanced</strong> contains more configuration options usually only needed to larger OPUS systems;</li>\r\n    </ul>From time to time other menus will appear as you manipulate objects, most notably students and companies, to help you deal with these. Also a <strong>recent</strong> menu will appear to allow you to more rapidly get back to objects you have been working with in this session.\r\n  <br />',24),(1,'RootHome',NULL,NULL,'Welcome message for Root Users','<p>\r\nWelcome. You are a super-admin user on this system (root user). This user is unconstrained by the policy system, and can perform almost any action within OPUS, including unwise ones. You should not use a user of this power without appropriate training.</p>\r\n  <p>Above, you will see you main menu, which you will use to manipulate OPUS. The sections are:</p>\r\n  <ul>\r\n    <li><strong>home</strong> which contains this page, an ability to !
 look at company activity and change your password;</li>\r\n    <li><strong>directories</strong> which will be the main menu you use day-to-day to work with students, companies and vacancies;</li>\r\n    <li><strong>information</strong> which is used to look as status and get reports;</li>\r\n    <li><strong>configuration</strong> which will be needed to set up OPUS and modify it\'s behaviour;</li>\r\n    <li><strong>advanced</strong> contains more configuration options usually only needed to larger OPUS systems;</li>\r\n    <li><strong>superuser</strong> contains options to maintain OPUS and sensitive configuration.</li>\r\n  </ul>From time to time other menus will appear as you manipulate objects, most notably students and companies, to help you deal with these. Also a <strong>recent</strong> menu will appear to allow you to more rapidly get back to objects you have been working with in this session.\r\n  <br />',25),(1,'StudentHomeRequired2006',NULL,NULL,'Shown on Student!
  Home Page, 2006-07, ALL REQUIRED',NULL,26),(1,'StudentHome2007',5,NUL
L,NULL,'\r\n',56),(1,'StudentHome2007',2,NULL,'Messages for students on placement 2007','<B>First Visit Online Form</B><BR><BR>\r\n\r\nA review of the online forms being used to assess your placement is being conducted this year.<BR><BR>\r\n\r\nYour first visit form, when completed, will NOT have any of the radio buttons selected. Instead feedback, including a grade, will be provided in the field labelled \'Comments on and for the Student\'.<BR><BR>\r\n\r\nAs a result of this, the Assessment Information listed below your timeline will not be applicable. Do not worry about a zero appearing for your first visit.<BR><BR><BR>\r\n\r\n\r\n<B>Annual Placement Student Competition Launched</B><BR><BR>\r\n \r\nThe  competition is for new 2007/8 placement students, who are asked to compete to become our new \"bloggers\".  The winners will be asked to write three 300-word \"blogs\" about their ongoing placement experiences, over the course of the academic year, with payment of Â£200 for!
  completing all three. See pdf file in the Resources Section for details.<BR><BR>\r\n\r\nBoth competitions aim to help ASET promote the benefits of work-based learning by highlighting the value of such opportunities.  Closing date is Friday 26th October 2007.<BR><BR> \r\n',57),(1,'testpaste',NULL,NULL,'test','6 Drumgreenagh Road\r\nRathfriland\r\nCo Down\r\nBT34 5BW\r\n\r\n14 November 2003\r\n\r\nDear Sir or Madam\r\n\r\nI am a second year student studying BSc Computing Science at University of\r\nUlster at Jordanstown.  I enclose my Curriculum Vitae which details my\r\nexamination successes to date.\r\n\r\nAn integral part of my course is a thirty-two week industrial placement\r\nwhich takes place in Year 3.  I wish to secure a position in your\r\norganisation to complete this placement.\r\n\r\nI am interested in all areas of Information Technology and I hope I will\r\nhave the opportunity to put theory and acquired skills into practice once my\r\nwork placement commences.!
 \r\n\r\nI would like to have the opportunity to work in your business,
 becoming\r\ninvolved in maintenance, testing and configuration.  I know my hardware and\r\nsoftware skills would be of benefit to me in this work role.  I particularly\r\nenjoy the networking and systems design element of computing and would like\r\nto take an active part in an IT business.\r\n\r\nThrough my work programmes and part-time employment I have gained experience\r\nin public relations and communications.  I have also been able to manage my\r\nresponsibilities within different working environments.  I have developed\r\ntime-management, teamwork and problem solving techniques both within my\r\nstudies and work situations.  The responsibilities I undertook allowed me to\r\nwork on my own initiative.  My part-time employment has allowed me to\r\nincrease my understanding and knowledge of technological advances in sales\r\nprocedures.  I am occasionally appointed to carry out supervisory\r\nresponsibilities.  Through my volunteer work in the community I have\r\nenhanc!
 ed my social skills.\r\n\r\nI would appreciate if you would contact me and let me know if you may be\r\nable to offer me the opportunity to complete my placement in your\r\norganisation.  If you require further information please do not hesitate to\r\ncontact me on 07708505189 (mobile), 02840630105 (home) or by mail\r\nbriegefitzpatrick@hotmail.com.\r\n\r\nYours faithfully\r\n\r\n\r\nBriege Fitzpatrick (Miss)\r\n\r\nEnc\r\n',27),(1,'AdminAdminAdminList',NULL,'admin','Shown in Admin editor before Admin listing','The following users are admin users on the system. The extent of their powers is determined by both their default policy, which defines a maximum upper bound on their powers, and any additional policy that might be enforced over a specific school or course. Admin users only have powers over the specific schools and courses they are granted power over.<BR><BR>',28),(1,'AdminAdminPolicyEdit',NULL,'admin','Show in the Admin editor during a policy edit session','<B>Warni!
 ng! Note that policies are usually shared by many individuals, and so 
altering the policy will affect all those users.</B><BR><BR>\r\n\r\nThe security system used in the website is determined by a mixture of a specific hiararchy of users (super-admin and admin users) and policies. These policies restrict the powers of admin users, and in some cases other users like course directors. Only root users can change policies.<BR><BR>\r\n\r\nPolicies consist of <B>categories</B> which are shown here as divisions in the table above and <B>permissions</B> which allow a certain action within a category.<BR><BR>\r\n\r\nEven if an administrator has a certain permission in their default policy, they may not be able to exert it over a given student for example because\r\n<UL>\r\n<LI>they have no permission for the school or course the student belongs to; or</LI>\r\n<LI>there is an additional policy of lower level defined against them for that school or course.</LI>\r\n</UL>\r\n\r\n',29),(1,'AdminAdminPolicyDelete',NULL,'admin','Shown in Admin Editor when a p!
 olicy is to be deleted','You have selected to delete a policy from the system. This should not normally be done, be aware that removing the policy may cause many admin accounts to stop normal functioning.',30),(1,'StudentHomePlaced',NULL,NULL,'Shown on Student Home Page,  All Yrs,  ALL PLACED',NULL,31),(1,'StudentHomePlaced2006',NULL,NULL,'Shown on Student Home Page, 2006-07, ALL PLACED',NULL,53),(1,'StudentHomePlaced2006',1,NULL,'StudentHomePLACED, SEME-2006','<h4>Students Returned from Placement 2006-07</h4>\r\n<CENTRE>(This announcement last update: Mon 17 Dec 07 14:40)</CENTRE><BR><BR>\r\n\r\n<B>Placement Results</B><BR>\r\nAll elements of assessment have now been added to OPUS Assessment Information (with a few exceptions which are in progress).<BR>\r\nPlease note:<BR>\r\n- where an Employer Assessment has not been completed, the final result will be calculated as the achieved results.taken as a percentage of 80 (ie excluding the 20 marks for the Employer Assessment)<B!
 R>\r\n- the results on OPUS will be communicated to the Registry in ea
rly Jan 08 so that the Student Record System may show the same value as OPUS.  Until this happens there will be a difference in the two records in some cases.  The true result is that on OPUS.<BR>\r\n- all results are provisional until approved by a Board of Examiners (in Jun 08), but are unlikely to change.<BR><BR>\r\n\r\nThanks for your patience in waiting for the completed marks.\r\n<BR><BR>\r\n\r\n<B>Employment</B><BR>\r\nYou will find from time to time vacancies promoted on this web site with the title \'Graduate - Company Name - Job Title\'.  These are aimed at you, the student in final year.  If you are interested in the job follow the instructions in the job document or description.<BR><BR>\r\n\r\nR J Laird<BR>\r\nIndustrial Placement Coordinator<BR>\r\nSchool of Electrical and Mechanical Engineering<BR>\r\nTel: 028 9036 6264<BR>\r\nE Mail: rj.laird@ulster.ac.uk<BR><BR>\r\n\r\n\r\n___________________________________________________<BR>\r\n',54),(1,'StudentHome2008',8!
 ,NULL,'Messages for students unplaced 2008 JN','<B>This announcement applies to students in the Jordanstown-based Computing School only.</B><BR>\r\n\r\nStudents whose CV does not pass the minimum quality threshold will NOT be able to use their CV to apply for jobs via the PDSystem.  If your CV is in this category you will need to make an appointment to meet with Edwin Curran, bringing along a paper copy of your CV.  While every effort will be made facilitate  you there will be an unavoidable delay.  The date when your CV meets the minimum quality threshold will be noted.<BR><BR>\r\n',65),(1,'StudentHomeRequired2008',1,'','SEME Student Home Required 2008','<h4>ANNOUNCEMENTS for SEME STUDENTS who REQUIRE PLACEMENT in 2008</h4>\r\n<p>(This announcement last update: Mon 10 Mar 08 12:30)<br /><br /><strong>Welcome</strong><br />Welcome to the OPUS Web Site. Here you will see vacancy promotions, your applications (bids), the status of your bid, company information, frequent annou!
 ncements updates, personal notes of \'significant occurrences\' affect
ing you and more details as the year proceeds.<br /><br /><strong>Preparation Programme</strong><br /><strong></strong><strong>Week 7 </strong>Update on OPUS web site following recent upgrade to v4<br /><br /><strong>Placement Status</strong><br />All students are required to advise R J Laird of a placement offer when received. Advise the company name, vacancy to be taken, start date and salary to R J Laird by E Mail or telephone, details below.<br /><br /><strong>Faculty of Computing and Engineering Policy on Industrial Placement</strong><br />All students are asked to note the following policy:<br />\'.... that on courses where Placement was mandatory students would not be permitted to proceed to final year without having first completed Placement.\' <br />The Faculty of Computing and Engineering places no restrictions on the geographic location of any approved placement.<br /><strong>This means that enless a student is formally EXEMPT from placement (or where placement is!
  voluntary) all students in good academic standing should be progressing to placement. In the context of placement \'good academic standing\' means having passed all year 2 modules with the possible exception of any one module to be completed following the Sep 08 Board of Examiners, ie one module may be carried into placement.</strong><br /><br /><strong>CV Completion</strong><br />You must ensure that your CV is complete before you bid for any vacancy. If any CV is found to be incomplete (yet designated COMPLETE) when used for a \'bid\', the \'bid\' will be removed. Subsequent use of an incomplete CV will result in SUSPENSION from use of the OPUS system to obtain placement.<br /><br /><strong>General Company Search</strong><br />Please use any of the following sites to search for any company:<br /><br />www.kompass.com - for companies worldwide.<br />www.kellysearch.com<br />www.applegate.co.uk - for companies in UK and RoI.<br />www.bionorthernireland.com - for biomedical!
  companies.<br /><br />In either site search for locality or company a
ctivity; find company\'s web site; look for careers or training or jobs or recruitment; look for internship, placement, co-op or sponsorship.<br /><br />R J Laird<br />Industrial Placement Coordinator<br />School of Electrical and Mechanical Engineering<br />Tel: 028 9036 6264<br />E Mail: rj.laird@ulster.ac.uk<br />___________________________________________________</p>',63),(1,'StudentHome2004',NULL,NULL,'Shown on Student Home Page, 2004-05, ALL','Welcome to OPUS - the management system for all aspects of work-integrated learning and placement - developed at the University of Ulster, School of Electrical and Mechanical Engineering.<BR><BR>\r\n\r\nNo further announcements.<BR><BR>\r\n\r\nR J Laird<BR>\r\nIndustrial Placement Coordinator<BR>\r\nSchool of Electrical and Mechanical Engineering<BR>\r\nTel: 44 (0)28 9036 6264<BR>\r\nE Mail: rj.laird@ulster.ac.uk<BR>',32),(1,'AdminNewStudent',NULL,NULL,'Used for creation of new student form','<B>Warning</B> This script now only c!
 reates new\r\nstudent users. Users of other categories are\r\ncreated in their appropriate directories.\r\nThis script is only intended for very occaisional use. The more powerful Import Data script should be used for most cases. Note that import data will not overwrite existing students and so can be used repeatedly as CSV files becomes more complete.\r\n<BR><BR>\r\n\r\nPlease be careful to use the correct course when creating a new student. Remember you will only have access to students in courses you are authorised for.<BR><BR>\r\n\r\nThe title, surname and student number are compulsory fields.\r\n',33),(1,'StudentAddCompany',NULL,NULL,'Shown to students just prior to selecting a company','<B>Warning</B> You are about to select a company, so that this company will be able to see your CV details with immediate effect.<BR>\r\nIt is <B>essential</B> that your CV is in good order before you do this. Although you might continue to update your CV a company that downloads a poo!
 r or incomplete CV from you may not check for updates later for any st
udent. If your CV is not in good order you could seriously damage your chances of employment with this company.<BR><BR>\r\n\r\nIt is possible for you to declare a <B>preferred</B> CV format you would like this company to view. Please note that in the future it will be possible for them to override this format, but they will be notified that you have a preference. You may enter text into a covering letter, but it is possible that some companies will ignore such letters.<BR><BR>\r\n',34),(1,'StudentCompaniesEditApp',NULL,NULL,'Shown before a student edits an existing application','Please note that there is no guarantee that a\r\ncompany will read your cover letter.\r\n\r\n<BR><BR>\r\nPlease ensure that the CV template you are using\r\nis complete <B>before</B> updating your application.',35),(1,'StudentApplicationsView',NULL,NULL,'Shown before list of applications for student.','Here is a list of your applications to companies.\r\nThis page gives you information about whether\!
 r\na company has seen your application yet, and\r\nwhen they last looked at it.\r\n\r\n<BR><BR>\r\nIt is also possible to update your cover letter\r\nand preferred CV.\r\n<BR><BR>\r\n',36),(1,'PDSCVFetchFailure',NULL,'all','Shown when a CV Fetch from the PDS Fails.','<title>Unable to fetch CV</title>\r\n\r\n',37),(1,'StudentHome2005',NULL,NULL,'Shown on Student Home Page, 2005-06, ALL','Welcome to OPUS - the management system for all aspects of work-integrated learning and placement - developed at the University of Ulster, School of Electrical and Mechanical Engineering.<BR><BR>',38),(1,'SupervisorHome',NULL,NULL,'Shown to Supervisors when they login','Welcome to OPUS - the management system for all aspects of work-integrated learning and placement - developed at the University of Ulster, School of Electrical and Mechanical Engineering.<BR><BR>\r\n\r\nYou can use this system to:\r\n<ul>\r\n  <li>check information recorded for the placement you are supervising;</li>\r\n  <li!
 >see the details of the Academic Tutor who will be visiting your stude
nt once they are appointed;</li>\r\n  <li>see and carry out any assessments enabled online for your student;</li>\r\n  <li>access RESOURCES from the menu on the left which give more information about courses, assessment regimes and lots more.</li>\r\n</ul>\r\nIf you supervise more than one student you will need to use your seperate login details appropriate for each student, as only one student appears under one set of login details.',39),(1,'StudentHome2005',1,NULL,'Student Home Announcement, 2005-06, SEME ALL','<h4>ANNOUNCEMENTS</h4>\r\n<CENTRE>(This announcement last update: Mon 04 Dec 06 15:40)</CENTRE><BR><BR>\r\n\r\n<B>Industrial Placement Results</B><BR>\r\nDue to late receipt of some reports the placement marks as displayed on OPUS may not be the same as those presented on the Student Record System.  In early new year I will have advised the Student Record System of the corrected mark, which is the mark on OPUS.<BR><BR>\r\n\r\n<B>Graduate Vacancies</B><BR>\r\nFrom ti!
 me to time adverts for Graduate Vacancies will appear on this system.  These vacancies will be designated \'Graduate - Company Name - Job Title\' and they will be promoted so that you may follow up the instructions in the advert.  It is not possible to bid for the graduate vacancy on this system (yet).<BR><BR>\r\n\r\nR J Laird<BR>\r\nIndustrial Placement Coordinator<BR>\r\nSchool of Electrical and Mechanical Engineering<BR>\r\nTel: 44 (0)28 9036 6264<BR>\r\nE Mail: rj.laird@ulster.ac.uk<BR>\r\n',43),(1,'StaffHome',2,NULL,'Shown to staff on their home page','<h4>ANNOUNCEMENTS</h4>\r\n<CENTRE>(This announcement last update: Mon 20 Nov 06 15:30)</CENTRE><BR><BR>\r\nWelcome to OPUS.<br><br>\r\n<B>Computing Placement Visitors</B><BR>\r\n\r\nPlease note the menu on your left. You can use this site to\r\n<ul>\r\n  <li>view information for students for which you are a Placement Visitor;</li>\r\n  <li>file assessment results for your students online;</li>\r\n</ul>\r\n\r\n<B>NB</B> F!
 irst visit should be completed by 15 December 2006 and the second visi
t by 30 April 2007.<BR><BR>\r\n\r\nA lot of work has gone into making this assessment available online and there may be some residual bugs or anomalies. There is ongoing effort to minimize these.  Please flag any such issues as soon as you notice them.<BR><BR>\r\n\r\nIn addition, if you are a Course Director, you can use the Student Directory to browse your students and see their progress in the placement operation. If that link does not appear for you, or if the list of courses shown is incorrect, please contact someone in your help directory.<BR><BR>\r\n\r\n\r\n\r\n',44),(1,'StudentHome2007',8,NULL,'spare',NULL,45),(1,'StaffHome',1,'','Staff Home Page Announcement','<h4>ANNOUNCEMENTS</h4>\r\n<p>(This announcement last update: Mon 10 Mar 08 14:18)<br /><br /><strong>Student Technical Reports</strong><br />These reports are issued 10 Mar 08 for assessment and reporting online on OPUS by <strong>13 Apr 08</strong>.</p>\r\n<p><strong>First Visits</strong><br />These should be !
 complete and reported on OPUS.</p>\r\n<p><strong>Final Visits</strong></p>\r\n<p>Please ensure that these visits and the online reports are completed BEFORE your&nbsp;students complete their placements.&nbsp; Note,&nbsp;some students will complete their placement in May 08.</p>\r\n<p>R J Laird<br />Industrial Placement Coordinator<br />School of Electrical and Mechanical Engineering<br />Tel: 028 9036 6264<br />E Mail: rj.laird@ulster.ac.uk</p>',46),(1,'StudentHomePlaced',1,NULL,'StudentHomePLACED, SEME-All Yrs','<CENTRE><h4>STUDENTS in PLACEMENT</h4></CENTRE>\r\n<CENTRE>(This announcement last update: Mon 22 Oct 07, 13:30)</CENTRE><BR>\r\n\r\nCongratulations, you are now considered to be in a University-supervised Industrial Placement with the organisation detailed at Placement Information below.<BR><BR>\r\n\r\nIf the information does not show the correct  <B>Position, Start Date and Salary</B>, you are requested to advise R J Laird soonest.<BR><BR>\r\n\r\nYou <B>MUST</B> !
 enter the necessary information at  <B>Work Phone</B>, <B>Work E Mail<
/B> and all under <B>Industrial Supervisor Contact Details</B>.  Your Industrial Supervisor is the person in your employment who is assigned by your employer to look afer your interests.  You are NOT to enter your personal details in the fields for your Industrial Supervisor.  You are requested to follow all instructions relating to this placement.  <B>Failure to comply with these instructions will result in loss of marks for the Diploma in Industrial Studies (DIS).</B><BR><BR>\r\n\r\n<B>Academic Tutor</B>  You will find the name and contact details of your Academic Tutor lower on this page.  You are asked to contact him/her now to arrange the date of the First Visit.  Ensure that your Industrial Supervisor will be available on the agreed date.<BR><BR>\r\n\r\n<B>PDP Return</B>  If you have not sent your PDP to R J Laird you must do so now.  This request was included in the documents which were referenced in the E Mail entitled \'Ind Pl 07-08 - Instructions\' which was sent t!
 o you earlier this summer.<BR><BR>\r\n\r\nR J Laird<BR>\r\nIndustrial Placement Coordinator<BR>\r\nSchool of Electrical and Mechanical Engineering<BR>\r\nTel: 028 9036 6264<BR>\r\nE Mail: rj.laird@ulster.ac.uk<BR>\r\n___________________________________________________<BR><BR>',50),(1,'StudentHome2007',7,NULL,NULL,NULL,55),(1,'StudentHomePlaced2007',1,NULL,'Shown on Student Home Page, 2007-08, SEME PLACED',NULL,51),(1,'StudentHomeRequired2006',1,NULL,'StudentHomeREQUIRED, SEME-2006','<h4>ANNOUNCEMENTS</h4>\r\n<CENTRE>(This announcement last update: Mon 27 Aug 07  15:05)</CENTRE><BR><BR>\r\n\r\n<B>Unplaced Students</B><BR>\r\nAny student who has not been in a University-supervised Industrial Placement in the period Summer 2006 - Summer 2007 is requested to note the following policy of the Faculty of Computing and Engineering:<BR>\r\nâ€˜It was AGREED that on courses where Placement was mandatory students would not be permitted to proceed to final year without having first comp!
 leted Placement.â€™ <BR>\r\nThe Faculty of Computing and Engineering p
laces no restrictions on the geographic location of any approved placement.<BR>\r\n<B>This means that any unplaced student from the 2006-07 placement year is NOT ELIGIBLE to proceed to the final year of their course unless they are EXEMPT by the Dean of the Faculty.</B><BR>\r\nTo obtain guidance of seeking EXEMPTION contact R J Laird at the communication details below.<BR><BR>\r\n\r\nR J Laird<BR>\r\nIndustrial Placement Coordinator<BR>\r\nSchool of Electrical and Mechanical Engineering<BR>\r\nTel: 44 (0)28 9036 6264<BR>\r\nE Mail: rj.laird@ulster.ac.uk<BR>\r\n___________________________________________________',52),(1,'SupervisorHome2007',1,NULL,'SupervisorHome, SEME-2007','<h4>ANNOUNCEMENTS</h4>\r\n<CENTRE>(This announcement last update: Mon 27 Aug 07 16:00)</CENTRE><BR><BR>\r\n\r\n<B>ROLE OF INDUSTRIAL SUPERVISOR</B><BR><BR>\r\nWelcome to the OPUS web site and thanks for your support to our Industrial Placement programme in the role as an \'Industrial Supervisor\'.<BR><BR!
 >\r\n\r\nYou may find helpful guidance for this role at INFORMATION | RESOURCES (see tab above), \'SEME07 - Guidance for the Industrial Supervisor 2007-08\'.  I ask that you review this document and support our student accordingly.<BR><BR>\r\n\r\n<B>EMPLOYER ASSESSMENT</B><BR><BR>\r\n\r\nYou are asked to complete the EMPLOYER ASSESSMENT (found under ASSESSMENT INFORMATION at the bottom of this page) for the student named at the top of this page.  The online report should be completed towards the end of the placement period and certainly before <B>31 Jul 08</B> to enable compilation of marks.  There is no need for E Mails or printed copies - completion of the report online and \'submitting it\' is sufficient.<BR><BR>\r\n\r\nThanks or your support.<BR><BR>\r\n\r\nR J Laird (Ron)<BR>\r\nIndustrial Placement Coordinator<BR>\r\nSchool of Electrical and Mechanical Engineering<BR>\r\nTel: 44 (0)28 9036 6264<BR>\r\nE Mail: rj.laird@ulster.ac.uk<BR>',62),(1,'testbug',NULL,NULL,'test!
  of bug filed','blah',59),(1,'StudentHome2006',2,NULL,'Important annou
ncement ','<B>Important announcement </B><BR><BR>\r\n\r\nThis is the first year that we have implemented  the online mark system. A number of issues have arisen which need to be dealt with - as a result no more marks are being placed online for this cohort of students.  We realise that this may be a little frustrating to some students but placement marks will be released in the normal way, later in the year.<BR><BR>\r\n',58),(1,'SupervisorHome2006',1,NULL,'SupervisorHome, SEME-2006','<h4>ANNOUNCEMENTS</h4>\r\n<CENTRE>(This announcement last update: Mon 06 Aug 07 13:00)</CENTRE><BR><BR>\r\n\r\n<B>ROLE OF INDUSTRIAL SUPERVISOR</B><BR><BR>\r\nWelcome to the OPUS web site and thanks for your support to our Industrial Placement programme in the role as an \'Industrial Supervisor\'.<BR><BR>\r\n\r\nYou may find helpful guidance for this role at INFORMATION | RESOURCES (see tab above), \'SEME06 - Guidance for the Industrial Supervisor 2006-07\'.  I ask that you review this document !
 and support our student accordingly.<BR><BR>\r\n\r\n<B>EMPLOYER ASSESSMENT</B><BR><BR>\r\n\r\nYou are asked to complete the EMPLOYER ASSESSMENT (found under ASSESSMENT INFORMATION at the bottom of this page) for the student named at the top of this page.  The online report should be completed towards the end of the placement period and certainly before <B>31 Jul 07</B> to enable compilation of marks.  There is no need for E Mails or printed copies - completion of the report online and \'submitting it\' is sufficient.<BR><BR>\r\n\r\nThanks or your support.<BR><BR>\r\n\r\nR J Laird (Ron)<BR>\r\nIndustrial Placement Coordinator<BR>\r\nSchool of Electrical and Mechanical Engineering<BR>\r\nTel: 44 (0)28 9036 6264<BR>\r\nE Mail: rj.laird@ulster.ac.uk<BR>',60),(1,'StudentHomeRequired2007',1,NULL,'StudentHomeREQUIRED, SEME-2007','<h4>ANNOUNCEMENTS for SEME STUDENTS who REQUIRE PLACEMENT</h4>\r\n<CENTRE>(This announcement last update: Mon 27 Aug 07 14:50)</CENTRE><BR><BR>\r\n\r\n<B!
 >Placement Status</B><BR>\r\nAll students are required to advise R J L
aird of a placement offer when received.  Advise the company name, vacancy to be taken, start date and salary to R J Laird by E Mail or telephone, details below.<BR><BR>\r\n\r\n<B>Faculty of Computing and Engineering Policy on Industrial Placement</B><BR>\r\nAll students are asked to note the following policy:<BR>\r\nâ€˜It was AGREED that on courses where Placement was mandatory students would not be permitted to proceed to final year without having first completed Placement.â€™ <BR>\r\nThe Faculty of Computing and Engineering places no restrictions on the geographic location of any approved placement.<BR>\r\n<B>This means that enless a student is formally EXEMPT from placement (or where placement is voluntary) all students in good academic standing should be progressing to placement.  In the context of placement \'good academic standing\' means having passed all year 2 modules with the possible exception of any one module to be completed following the Sep 07 Board of Examin!
 ers, ie one module may be carried into placement.</B><BR><BR>\r\n\r\n<B>CV Completion</B><BR>\r\nYou must ensure that your CV is complete before you bid for any vacancy.  If any CV is found to be incomplete (yet designated COMPLETE) when used for a \'bid\', the \'bid\' will be removed.  Subsequent use of an incomplete CV will result in SUSPENSION from use of the OPUS system to obtain placement.<BR><BR>\r\n\r\n<B>General Company Search</B><BR>\r\nPlease use any of the following sites to search for any company:<BR><BR>\r\n\r\nwww.kompass.com  - for companies worldwide.<BR>\r\nwww.kellysearch.com<BR>\r\nwww.applegate.co.uk  - for companies in UK and RoI.<BR>\r\nwww.bionorthernireland.com - for biomedical companies.<BR><BR>\r\n\r\nIn either site search for locality or company activity; find company\'s web site; look for careers or training or jobs or recruitment; look for internship, placement, co-op or sponsorship.<BR><BR>\r\n\r\nR J Laird<BR>\r\nIndustrial Placement Coordinat!
 or<BR>\r\nSchool of Electrical and Mechanical Engineering<BR>\r\nTel: 
028 9036 6264<BR>\r\nE Mail: rj.laird@ulster.ac.uk<BR>\r\n___________________________________________________<BR>',61),(1,'StudentApplicationsViewIAESTE2008',NULL,NULL,NULL,NULL,66),(1,'StudentApplicationsViewIAESTE2008',2,NULL,'IAESTE 2008 Application','\r\n<B> A number of students have applied to IAESTE.  This scheme will give you valuable experience and we would encourage you to pursue this avenue in conjunction with a placement.   Most of the IAESTE opportunities are short term i.e. around three months and could possibly be fitted in before or after your placement.<B>',67),(1,'StudentHome2007IAESTE2008',NULL,NULL,NULL,NULL,68),(1,'StudentHome2007/2008',NULL,NULL,'IAESTE Applications 2008 ','<B> A number of students have applied to IAESTE.  This scheme will give you valuable experience and we would encourage you to pursue this avenue in conjunction with a placement.   Most of the IAESTE opportunities are short term i.e. around three months and could possibly be fitted in !
 before or after your placement.<B>',69);
/*!40000 ALTER TABLE `help` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `automail`
--

LOCK TABLES `automail` WRITE;
/*!40000 ALTER TABLE `automail` DISABLE KEYS */;
INSERT INTO `automail` VALUES (1,'NewPassword','%afirstname% %asurname% <%aemail%>','%rfirstname% %rsurname% <%remail%>','','%afirstname% %asurname% <%aemail%>','OPUS: Account information for University of Ulster placement system','Sent to users on creation, or when a password is changed','Dear %rtitle% %rsurname%,\r\n\r\nThis is an automated message from the Placement Management System at the University of Ulster.\r\n\r\nYou are receiving this message either because a new password has just been generated for your account or because an account has just been created for you.\r\n\r\nTo use the web based system, please go to\r\n\r\n%conf_website%\r\n           \r\nand click on the option to login. When prompted please use the credentials shown below.\r\n\r\nusername : %username%\r\npassword : %password%\r\n\r\nOnce you login you will be able to change your password if you wish. Please feel free to ask for any further guidance.\r\n\r\n%atitle% %afirstname% %asurname%\r\n%apositi!
 on%',1),(1,'StudentOnPlaced','%afirstname% %asurname% <%aemail%>','%rfirstname% %rsurname% <%remail%>',NULL,'%afirstname% %asurname% <%aemail%>','Congratulations, you have been placed','Sent to a student to confirm placed','Dear %rfirstname%,\r\n\r\nCongratulations, you have been successfully placed. Please see the details below for more information.\r\n\r\nCompany    : %pcompany%\r\nPosition   : %pposition%\r\nStart      : %pstart%\r\nEnd        : %pend%\r\nSupervisor : %psupervisor%\r\n\r\nPlease fill in any information missing above on the website as soon as possible.\r\n\r\nContinue to check the placement website\r\n\r\n%website%\r\n\r\nfor information on your assessment programme and academic tutor as it becomes available.\r\n\r\n%atitle% %afirstname% %asurname%\r\n%aposition%',2),(1,'CompanyOnClosed','Colin Turner <c.turner@ulster.ac.uk>','%rfirstname% %rsurname% <%remail%>','','Colin Turner <c.turner@ulster.ac.uk>, Ron Laird <rj.laird@ulster.ac.uk>','UU OPUS: One of !
 the your vacancies has closed','Sent to listed contact when a vacancy 
closes','Dear %rtitle% %rsurname%,\r\n\r\nThis is an automated message from the industrial placement system for %conf_institution%:\r\n\r\n%conf_website%\r\n\r\nOne of your vacancies listed on our system has just closed. If you wish to reopen it, please set a new closing date and change the status to \"open\" to allow automated applications, or \"special\" if you only allow applications via some other means.\r\n\r\nVacancy\r\n-------\r\n\r\n%custom_vacancydesc%\r\n\r\nCompany\r\n-------\r\n\r\n%custom_companyname%\r\n\r\nThere are currently %custom_applicationcount% applicants.\r\n\r\nYou can edit your vacancy (should you for example wish to reopen it) here\r\n\r\n%conf_website%/opus/%custom_editurl%\r\n\r\nor look at your applicants here\r\n\r\n%conf_website%/opus/%custom_manageurl%\r\n\r\nor just log in normally to otherwise maintain your account.\r\n\r\n%atitle% %afirstname% %asurname%\r\n%aposition%',3),(1,'CourseStats',NULL,'%rtitle% %rsurname% <%remail%>',NULL,NULL,'Co!
 urse statistics for %custom_coursename%','Send along with statistics for a course','Dear %rtitle% %rsurname%,\r\n\r\nPlease find enclosed....\r\n\r\n\r\n%custom_table%\r\n\r\n',4),(1,'NewPassword_Contact','%afirstname% %asurname% <%aemail%>','%rfirstname% %rsurname% <%remail%>','','%afirstname% %asurname% <%aemail%>','UU OPUS : Your account details for managing placement recruitment','Sent to company HR contacts upon account creation','Dear %rtitle% %rsurname%,\r\n\r\nThis is an automated message from the Placement Management System at the University of Ulster. You will be able to use this account to examine your job advertisments and monitor student applications.\r\n\r\nYou are receiving this message either because a new password has just been generated for your account or because an account has just been created for you.\r\n\r\nTo use the web based system, please go to\r\n\r\n%conf_website%\r\n           \r\nand click on the option to login. When prompted please use the c!
 redentials shown below.\r\n\r\nusername : %username%\r\npassword : %pa
ssword%\r\n\r\nOnce you login you will be able to change your password if you wish. Please feel free to ask for any further guidance.\r\n\r\n%atitle% %afirstname% %asurname%\r\n%aposition%',5),(1,'NewPassword_Staff','%afirstname% %asurname% <%aemail%>','%rfirstname% %rsurname% <%remail%>','','%afirstname% %asurname% <%aemail%>','OPUS: Your account details','New password sent to Academic Staff','Dear %rtitle% %rsurname%,\r\n\r\nThis is an automated message from the Placement Management System at the University of Ulster. You can use this account to see details on the students you are allocated, as well as to record their assessment.\r\n\r\nYou are receiving this message either because a new password has just been generated for your account or because an account has just been created for you.\r\n\r\nTo use the web based system, please go to\r\n\r\nhttp://%conf_website%\r\n           \r\nand click on the option to login. When prompted please use the credentials shown below.\r\n!
 \r\nusername : %username%\r\npassword : %password%\r\n\r\nOnce you login you will be able to change your password if you wish. Please feel free to ask for any further guidance.\r\n\r\n%atitle% %afirstname% %asurname%\r\n%aposition%',6),(1,'NewPassword_Supervisor','%afirstname% %asurname% <%aemail%>','%rfirstname% %rsurname% <%remail%>',NULL,'%afirstname% %asurname% <%aemail%>','Your account details for supervising your placement student','New Password Information for Workplace Supervisors','Dear %rtitle% %rsurname%,\r\n\r\nThis is an automated message from the Placement Management System at the University of Ulster. This account is to help you supervise one placement student; you may receive more than one set of details if you are looking after more than one student - so please retain any other username and password you may already have.\r\n\r\nYou can use this account to see details recorded about the placement, contact staff in the university who can assist with any issue!
 s, and often to assess the student at an appropriate time in the acade
mic year when you are requested to do so.\r\n\r\nWe appreciate all your help with our placement operation.\r\n\r\nYou are receiving this message either because a new password has just been generated for your account or because an account has just been created for you.\r\n\r\nTo use the web based system, please go to\r\n\r\nhttp://%conf_website%\r\n           \r\nand click on the option to login. When prompted please use the credentials shown below.\r\n\r\nusername : %username%\r\npassword : %password%\r\n\r\nOnce you login you will be able to change your password if you wish. Please feel free to ask for any further guidance.\r\n\r\n%atitle% %afirstname% %asurname%\r\n%aposition%',7),(1,'PhoneHome_Install','%afirstname% %asurname% <%aemail%>','opus-stats@foss.ulster.ac.uk','','','New OPUS installation','This is used to send an email to UU upon installation, only with your permission','New OPUS install\r\n\r\ninstitution: %conf_institution%\r\nurl: %conf_website%\r\nversion: %!
 conf_version%\r\n',8),(1,'PhoneHome_Periodic','%afirstname% %asurname% <%aemail%>','opus-stats@foss.ulster.ac.uk','','','OPUS Periodic Statistics','Non confidential information, send periodically with your consent, to the University of Ulster','institution: %conf_institution%\r\nurl: %conf_website%\r\nversion: %conf_version%\r\n\r\nstudents: %custom_students%\r\nroots: %custom_roots%\r\nadmins: %custom_admins%\r\ncontacts: %custom_contacts%\r\nstaff: %custom_staff%\r\nsupervisors: %custom_supervisors%\r\ncompanies: %custom_companies%\r\nvacancies: %custom_vacancies%\r\n',9);
/*!40000 ALTER TABLE `automail` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `assessment`
--

LOCK TABLES `assessment` WRITE;
/*!40000 ALTER TABLE `assessment` DISABLE KEYS */;
INSERT INTO `assessment` VALUES ('First Visit','First Visit','assessment/uu/first_visit_nomark.tpl',1),('Technical Report','Technical Report','assessment/uu/technical_report.tpl',2),('Second Visit','Final Visit','assessment/uu/final_visit.tpl',3),('Placement Report','Final Report','assessment/uu/placement_report.tpl',5),('Industrial Report','Supervisor\'s Report','assessment/uu/industrial_report.tpl',6),('Presentation','Presentation','assessment/uu/presentation.tpl',7),('Student Health & Safety','Health & Safety','assessment/uu/student_healthsafety.tpl',8),('First Visit (Assessed)','First Visit','assessment/uu/first_visit.tpl',9);
/*!40000 ALTER TABLE `assessment` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `assessmentgroup`
--

LOCK TABLES `assessmentgroup` WRITE;
/*!40000 ALTER TABLE `assessmentgroup` DISABLE KEYS */;
INSERT INTO `assessmentgroup` VALUES ('Default Scheme',NULL,1);
/*!40000 ALTER TABLE `assessmentgroup` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `assessmentstructure`
--

LOCK TABLES `assessmentstructure` WRITE;
/*!40000 ALTER TABLE `assessmentstructure` DISABLE KEYS */;
INSERT INTO `assessmentstructure` VALUES (2,'Description of Practice / Process mark','numeric',0,20,1,'mark1',1,1,'compulsory'),(2,'Understanding of Principles / Theory mark','numeric',0,20,1,'mark2',3,2,'compulsory'),(2,'Investigation / Research mark','numeric',0,20,1,'mark3',5,3,'compulsory'),(2,'Spelling / Punctuation mark','numeric',0,10,1,'mark4',7,4,'compulsory'),(2,'Use of English mark','numeric',0,10,1,'mark5',9,5,'compulsory'),(2,'Structure of Ideas mark','numeric',0,10,1,'mark6',11,6,'compulsory'),(2,'Presentation mark','numeric',0,10,1,'mark7',13,7,'compulsory'),(2,'Description of Practice / Process comments','textual',NULL,500,0,'comment1',2,8,'optional'),(2,'Understanding of Principles / Theory comments','textual',NULL,500,0,'comment2',4,9,'optional'),(2,'Investigation / Research comments','textual',NULL,500,0,'comment3',6,10,'optional'),(2,'Spelling / Punctuation comment','textual',NULL,500,0,'comment4',8,11,'optional'),(2,'Use of English comments','textual',NU!
 LL,500,0,'comment5',10,12,'optional'),(2,'Structure of Ideas comments','textual',NULL,500,0,'comment6',12,13,'optional'),(2,'Presentation comments','textual',NULL,500,0,'comment7',14,14,'optional'),(2,'General Comments','textual',NULL,1000,0,'comments',15,15,'optional'),(3,'Ability to describe and understanding of tasks performed','numeric',NULL,5,1,'A1',2,16,'optional'),(1,'Training / Experience programme arranged','checkbox',NULL,NULL,0,'check1',1,17,'optional'),(3,'Analytical Skills','numeric',NULL,5,1,'A2',3,18,'optional'),(3,'Attempts to be creative/innovative/display initiative','numeric',NULL,5,1,'A3',4,19,'optional'),(3,'Date of visit','assesseddate',NULL,NULL,0,'assesseddate',1,20,'compulsory'),(3,'Ability to describe the business of the employer','numeric',NULL,5,1,'B1',5,21,'optional'),(3,'Knowledge of the company/organisation and its structures','numeric',NULL,5,1,'B2',6,22,'optional'),(3,'Knowledge of role of others in the company/organisation.','numeric',NULL,!
 5,1,'B3',7,23,'optional'),(3,'Health and Safety','numeric',NULL,5,1,'B
4',8,24,'optional'),(3,'Environmental Awareness','numeric',NULL,5,1,'B5',9,25,'optional'),(3,'Integration within the company','numeric',NULL,5,1,'B6',10,26,'optional'),(3,'Flexibility and attitude to change','numeric',NULL,5,1,'C1',11,27,'optional'),(3,'Self Organisation','numeric',NULL,5,1,'C2',12,28,'optional'),(3,'Teamwork','numeric',NULL,5,1,'C3',13,29,'optional'),(3,'Leadership','numeric',NULL,5,1,'C4',14,30,'optional'),(3,'Information Technology','numeric',NULL,5,1,'D1',15,31,'optional'),(3,'Communication','numeric',NULL,5,1,'D2',16,32,'optional'),(3,'Career planning','numeric',NULL,5,1,'D3',17,33,'optional'),(3,'Log Book Inspection','checkbox',NULL,NULL,0,'logbook',18,34,'optional'),(3,'Comments on the student','textual',NULL,1000,0,'scomments',20,35,'optional'),(3,'Comments on the company','textual',NULL,1000,0,'ccomments',21,36,'optional'),(1,'Training / Experience programme comments','textual',NULL,500,0,'comment1',2,37,'optional'),(1,'Industrial Supervisor Appoint!
 ed','checkbox',NULL,NULL,0,'check2',3,38,'optional'),(1,'Industrial Supervisor comments','textual',NULL,500,0,'comment2',4,39,'optional'),(1,'Student Interviewed','checkbox',NULL,NULL,0,'check3',5,40,'optional'),(1,'Student interview comments','textual',NULL,500,0,'comment3',6,41,'optional'),(1,'Company Representative Interviewed','checkbox',NULL,NULL,0,'check4',7,42,'optional'),(1,'Company Representative Comments','textual',NULL,500,0,'comment4',8,43,'optional'),(1,'Log Book Inspected','checkbox',NULL,NULL,0,'check5',9,44,'optional'),(1,'Log Book comments','textual',NULL,500,0,'comment5',10,45,'optional'),(1,'Health and Safety Checklist Inspected','checkbox',NULL,NULL,0,'check6',11,46,'optional'),(1,'Health and Safety Checklist comments','textual',NULL,500,0,'comment6',12,47,'optional'),(1,'Student Accomodation Satisfactory','checkbox',NULL,NULL,0,'check7',13,48,'optional'),(1,'Student Accomodation comments','textual',NULL,500,0,'comment7',14,49,'optional'),(1,'Changes to !
 the Training / Experience Programme','textual',NULL,1000,0,'changes',1
5,50,'optional'),(1,'Comments on the Student and the Programme','textual',NULL,1000,0,'scomments',16,51,'optional'),(1,'Advice given to the student','textual',NULL,1000,0,'advice',17,52,'optional'),(1,'Assessment date','assesseddate',NULL,NULL,0,'assesseddate',18,53,'compulsory'),(3,'Lookbook is satisfactory?','checkbox',NULL,NULL,0,'logbookok',19,54,'optional'),(7,'Content (Assessor A)','numeric',NULL,5,1,'ContentA',1,55,'optional'),(7,'Content (Assessor B)','numeric',NULL,5,1,'ContentB',2,56,'optional'),(7,'Content (Assessor C)','numeric',NULL,5,1,'ContentC',3,57,'optional'),(7,'Content (Assessor D)','numeric',NULL,5,1,'ContentD',4,58,'optional'),(7,'Structure (Assessor A)','numeric',NULL,5,1,'StructureA',5,59,'optional'),(7,'Structure (Assessor B)','numeric',NULL,5,1,'StructureB',6,60,'optional'),(7,'Structure (Assessor C)','numeric',NULL,5,1,'StructureC',7,61,'optional'),(7,'Structure (Assessor D)','numeric',NULL,5,1,'StructureD',8,62,'optional'),(7,'Visuals (Assessor A)!
 ','numeric',NULL,5,1,'VisualsA',9,63,'optional'),(7,'Visuals (Assessor B)','numeric',NULL,5,1,'VisualsB',10,64,'optional'),(7,'Visuals (Assessor C)','numeric',NULL,5,1,'VisualsC',11,65,'optional'),(7,'Visuals (Assessor D)','numeric',NULL,5,1,'VisualsD',12,66,'optional'),(7,'Delivery (Assessor A)','numeric',NULL,5,1,'DeliveryA',13,67,'optional'),(7,'Delivery (Assessor B)','numeric',NULL,5,1,'DeliveryB',14,68,'optional'),(7,'Delivery (Assessor C)','numeric',NULL,5,1,'DeliveryC',15,69,'optional'),(7,'Delivery (Assessor D)','numeric',NULL,5,1,'DeliveryD',16,70,'optional'),(7,'Questions (Assessor A)','numeric',NULL,5,1,'QuestionsA',17,71,'optional'),(7,'Questions (Assessor B)','numeric',NULL,5,1,'QuestionsB',18,72,'optional'),(7,'Questions (Assessor C)','numeric',NULL,5,1,'QuestionsC',19,73,'optional'),(7,'Questions (Assessor D)','numeric',NULL,5,1,'QuestionsD',20,74,'optional'),(7,'Notes','textual',NULL,400,0,'Notes',21,75,'optional'),(8,'Emergency Procedures','',NULL,NULL,0,'e!
 mergency_procedures',1,76,'compulsory'),(8,'Health & Safety Procedure 
Received or Location Known','',NULL,NULL,0,'policy_received',2,77,'compulsory'),(8,'Location of First Aid box or station','',NULL,NULL,0,'firstaid_location',3,78,'compulsory'),(8,'First Aid Arrangements','',NULL,NULL,0,'firstaid_arrangements',4,79,'compulsory'),(8,'Fire Procedures and location of extinguishers','',NULL,NULL,0,'fire_procedures',5,80,'compulsory'),(8,'Accident reporting procedures ','',NULL,NULL,0,'accident_reporting',6,81,'compulsory'),(8,'COSHH regulations','',NULL,NULL,0,'coshh_regulations',7,82,'compulsory'),(8,'Manual handling procedures','',NULL,NULL,0,'handling_procedures',8,83,'compulsory'),(8,'Display screen equipment regulations or procedures','',NULL,NULL,0,'display_equipment',9,84,'compulsory'),(8,'Protective clothing arrangements','',NULL,NULL,0,'protective_clothing',10,85,'compulsory'),(8,'Instructions on equipment to be used in your work','',NULL,NULL,0,'equipment_instructions',11,86,'compulsory'),(8,'Any relevant risk assessments which have bee!
 n notified to you','',NULL,NULL,0,'risk_assessments',12,87,'compulsory'),(8,'Bullying and Harassment Policy & Procedure','',NULL,NULL,0,'bullying_policy',13,88,'compulsory'),(8,'Read UU Health & Safety - guidance for students on placement','',NULL,NULL,0,'uu_safety',14,89,'compulsory'),(8,'Other Health & Safety issues notified','',NULL,NULL,0,'other_hs',15,90,'compulsory'),(8,'Other issues','textual',NULL,1000,0,'issues',16,91,'optional'),(8,'Confirmation all issues raised and dealt with','checkbox',NULL,NULL,0,'compliance',17,92,'compulsory'),(6,'Interest in work','numeric',1,5,1,'interest',1,93,'compulsory'),(6,'Enterprise','numeric',1,5,1,'enterprise',2,94,'compulsory'),(6,'Organisation and Planning','numeric',NULL,5,1,'organisation',3,95,'compulsory'),(6,'Ability to Learn','numeric',NULL,5,1,'learn',4,96,'compulsory'),(6,'Quality of Work','numeric',NULL,5,1,'quality',5,97,'compulsory'),(6,'Quantity of Work','numeric',NULL,5,1,'quantity',6,98,'compulsory'),(6,'Judgement'!
 ,'numeric',NULL,5,1,'judgement',7,99,'compulsory'),(6,'Dependability\r
\n','numeric',NULL,5,1,'dependability',8,100,'compulsory'),(6,'Relations with Others','numeric',NULL,5,1,'relations',9,101,'compulsory'),(6,'Creativity','numeric',NULL,5,1,'creativity',10,102,'compulsory'),(6,'Communication Skills - Written Expression','numeric',NULL,5,1,'comm_written',11,103,'compulsory'),(6,'Communication Skills - Oral Expression','numeric',NULL,5,1,'comm_oral',12,104,'compulsory'),(6,'Acceptance of Criticism','numeric',NULL,5,1,'accept_crit',13,105,'compulsory'),(6,'Attendance','numeric',NULL,5,1,'attendance',14,106,'compulsory'),(6,'Punctuality','numeric',1,5,1,'punctuality',15,107,'compulsory'),(6,'Comments on the student\'s performance','textual',NULL,4000,0,'performance_comments',16,108,'optional'),(6,'Comments on the initial knowledge and skills of the student','textual',NULL,4000,0,'skills_comments',17,109,'optional'),(6,'Comments on the placement process','textual',NULL,4000,0,'process_comments',18,110,'optional'),(5,'Employer / Personal Work Mark'!
 ,'numeric',NULL,20,1,'mark1',1,111,'compulsory'),(5,'Employer / Personal Work Comment','textual',NULL,200,0,'comment1',2,112,'optional'),(5,'Innovation in the Organisation Mark','numeric',NULL,20,1,'mark2',3,113,'compulsory'),(5,'Innovation in the Organisation Comment','textual',NULL,200,0,'comment2',4,114,'optional'),(5,'Reflection on the Benefit of Placement Mark','numeric',NULL,30,1,'mark3',5,115,'compulsory'),(5,'Reflection on the Benefit of Placement Comment','textual',NULL,200,0,'comment3',6,116,'optional'),(5,'Spelling and Punctuation Mark','numeric',NULL,10,1,'mark4',7,117,'compulsory'),(5,'Spelling and Punctuation Comment','textual',NULL,200,0,'comment4',8,118,'optional'),(5,'Use of English Mark','numeric',NULL,10,1,'mark5',9,119,'compulsory'),(5,'Use of English Comment','textual',NULL,200,0,'comment5',10,120,'optional'),(5,'Presentation Mark','numeric',NULL,10,1,'mark6',11,121,'compulsory'),(5,'Presentation Comment','textual',NULL,200,0,'comment6',12,122,'optional!
 '),(5,'General Comments','textual',NULL,600,0,'comments',13,123,'optio
nal'),(9,'Personal Work Activities','numeric',NULL,5,1,'personal_work',1,124,'compulsory'),(9,'Personal Development Plan','numeric',NULL,5,1,'personal_development',2,125,'compulsory'),(9,'Placement Organisation Knowledge','numeric',NULL,5,1,'organisation_knowledge',3,126,'compulsory'),(9,'Student Log Book','numeric',NULL,5,1,'log_book',4,127,'optional'),(9,'Health & Safety matters raised','textual',NULL,400,0,'hs_matters',10,128,'optional'),(9,'Health & Safety advice given','textual',NULL,400,0,'hs_advice',11,129,'optional'),(9,'Student Accommodation','textual',NULL,400,0,'accommodation',12,130,'compulsory'),(9,'Comment on the student','textual',NULL,500,0,'comment_student',13,131,'optional'),(9,'Comment on the placement','textual',NULL,500,0,'comment_placement',14,132,'optional'),(9,'Student was visited','checkbox',NULL,NULL,0,'visit',15,133,'optional'),(9,'Visit date','assesseddate',NULL,NULL,0,'visit_date',16,134,'compulsory');
/*!40000 ALTER TABLE `assessmentstructure` ENABLE KEYS */;
UNLOCK TABLES;


--
-- Dumping data for table `cvgroup`
--

LOCK TABLES `cvgroup` WRITE;
/*!40000 ALTER TABLE `cvgroup` DISABLE KEYS */;
INSERT INTO `cvgroup` VALUES ('Default Group','Placement CV or an Archived CV may be used','allowCustom',5,1);
/*!40000 ALTER TABLE `cvgroup` ENABLE KEYS */;
UNLOCK TABLES;


--
-- Dumping data for table `language`
--

LOCK TABLES `language` WRITE;
/*!40000 ALTER TABLE `language` DISABLE KEYS */;
INSERT INTO `language` VALUES ('English','',1);
/*!40000 ALTER TABLE `language` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `mimetype`
--

LOCK TABLES `mimetype` WRITE;
/*!40000 ALTER TABLE `mimetype` DISABLE KEYS */;
INSERT INTO `mimetype` VALUES ('application/pdf','pdf','Adobe\'s Portable Document Format',1,'yes'),('application/msword','doc','Microsoft Word',2,'yes'),('video/quicktime','mov qt','Apple\'s Quicktime Videos',3,'yes'),('Aha, thank you for clarifying.  ','mov qt','Apple\'s Quicktime Videos',4,'yes'),('application/vnd.rn-realmedia','rm','Real Media Files',5,'yes');
/*!40000 ALTER TABLE `mimetype` ENABLE KEYS */;
UNLOCK TABLES;


--
-- Dumping data for table `policy`
--

LOCK TABLES `policy` WRITE;
/*!40000 ALTER TABLE `policy` DISABLE KEYS */;
INSERT INTO `policy` VALUES ('Placement Coordinator','list,create,edit','','list,create,edit,delete','students,photos','user','general,admin','list','create,edit,archive,list','create,edit,archive,list','create,edit','create,edit,delete','create,edit,archive,list,delete','create,edit,archive,list','list,create,viewCV,editCV,viewStatus,editStatus,viewCompanies,editCompanies,viewAssessments,editAssessments',1,1000,'list,create,edit,read,write','list,create,edit','list,create,edit'),('Placement Tutor','list','','','','user','general,admin','','list','edit,list','edit','edit','create,edit,list','list','list,viewCV,editCV,viewStatus,editStatus,viewCompanies,editCompanies,viewAssessments,editAssessments',2,100,'list,edit,read,write','list','list'),('Course Director','','','','','','',NULL,'','edit','',NULL,'','','list,viewStatus,viewCompanies,note',3,NULL,NULL,NULL,NULL),('Viewer','list','list','list','','user','',NULL,'list','list','','','list','list','list,viewCV,viewStatus,view!
 Companies,viewAssessments',4,10000,NULL,NULL,NULL);
/*!40000 ALTER TABLE `policy` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `vacancytype`
--

LOCK TABLES `vacancytype` WRITE;
/*!40000 ALTER TABLE `vacancytype` DISABLE KEYS */;
INSERT INTO `vacancytype` VALUES ('One Year, Full Time',10,NULL,1),('Summer Job',20,NULL,2),('Graduate Job',30,NULL,3);
/*!40000 ALTER TABLE `vacancytype` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `activitytype`
--

LOCK TABLES `activitytype` WRITE;
/*!40000 ALTER TABLE `activitytype` DISABLE KEYS */;
INSERT INTO `activitytype` VALUES ('Mechanical Engineering',1),('Electrical Engineering',2),('Electronics/Computing',3),('Biomedical Engineering',4),('Design/Consulting',5),('Manufacture/Operations',6),('Software Engineering',7),('Multimedia and Web Design',8),('Computer Science',9),('Mathematics and Statistics',10),('Business and Management',11),('Hospitality, tourism & leisure',12),('Construction Engineering',13),('Civil Engineering',14),('Quantity Surveying',15);
/*!40000 ALTER TABLE `activitytype` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2008-03-18  2:38:32
