Document: opus
Title: Debian opus Manual
Author: <insert document author here>
Abstract: This manual describes what opus is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/opus/opus.sgml.gz

Format: postscript
Files: /usr/share/doc/opus/opus.ps.gz

Format: text
Files: /usr/share/doc/opus/opus.text.gz

Format: HTML
Index: /usr/share/doc/opus/html/index.html
Files: /usr/share/doc/opus/html/*.html

  
